theme = "autumn_night"

[editor]
line-number = "absolute"
mouse = true
cursorline = true
color-modes = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right =  ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
